# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
 workflow_dispatch:
#   push:
#     branches: [ main ]
# #   pull_request:
#     branches: [ main ]
jobs:

  flutter_build:
    name: Run fultter build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter create helloworld
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: helloworld
          path: helloworld
