# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Test 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: create folder
      run: mkdir -p mytest 

    - name: create file
      run: echo hi > mytest/mytest.txt
    - uses: actions/upload-artifact@v2
      with:
        name: mytest
